### ISSUE TITLE
correct connection string usage

### ISSUE THREAD

**Issue by vitaly-t** [ryanhs/ncurated#1]
https://github.com/ryanhs/ncurated/blob/ff9d427ff1a1ce216132e7af09f15c5292ce3a03/src/streams/drivers/kafka/machines/createInstance.js#L39

should be:

```js
const brokers = connectionStringParsed.hosts.map(h => h.toString()); 

// if no hosts specified, `connectionStringParsed.hosts` will be `undefined`.
```

**Comment by ryanhs** [comment]
Thank you, will be patched soon.
